[package]
name = "gifcat"
version = "0.1.0"
authors = ["Chris Konstad <chriskon149@gmail.com>"]
description = "Plays gifs using ncurses."

[dependencies]
gif = "0.9.2"
ncurses = "5.86.0"
resize = "0.3.0"
clap = "*"
